### ISSUE TITLE
Talk getting participants test broken

### ISSUE THREAD

**Issue by provokateurin** [Viktoriaschule/dart-nextcloud#15]
Talk getting participants test is broken in some cases, because it returns some id which looks randomly generated and is not the user id. It's actually the same id used for the file path in my scenario

**Comment by provokateurin** [comment]
So this is a case where loginname != username. We need to add a test to fix this, but first create a case to trigger it manually on the dev/test NC instance.

**Comment by vauvenal5** [comment]
I think by making the admin user login with email address instead of username this can be triggered by default on the test instance. This way the more complicated case is the default case in the tests. Also, we should consider retrieving the real username for every client that requires the username, or how do you see it?
